export PROBLEM = 1082-Sum_of_Divisors-c++-mult-rapl-think-control-01-23-07-2024-14-36
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry11.txt ../test/entry12.txt ../test/entry13.txt ../test/entry14.txt ../test/entry15.txt ../test/entry17.txt 
all:
	+$(MAKE) -C last_exp/
clean:
	rm last_exp//*.exe last_exp//*.class
