export PROBLEM = 2185-Prime_Multiples-c++-mult-rapl-think-control-01-23-07-2024-14-36
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry02.txt ../test/entry03.txt 
all:
	+$(MAKE) -C last_exp/
clean:
	rm last_exp//*.exe last_exp//*.class
