export PROBLEM = 1634-Minimizing_Coins-c++-mult-rapl-think-control-01-23-07-2024-14-36
export CPPFLAGS = -DONLINE_JUDGE -std=c++17 -O2
export OUTPUT = > /dev/null 2>&1
export TEST = ../test/entry04.txt ../test/entry05.txt ../test/entry08.txt ../test/entry09.txt ../test/entry11.txt 
all:
	+$(MAKE) -C last_exp/
clean:
	rm last_exp//*.exe last_exp//*.class
