export PROBLEM = 1071-HPELITE-java
export OUTPUT = > /dev/null 2>&1
export TEST = ../../test/entry01.txt ../../test/entry02.txt
 
all:
#	+$(MAKE) -C fast
	+$(MAKE) -C lang
#	+$(MAKE) -C slow

clean:
#	rm fast/*.class lang/*.class slow/*.class  
	rm lang/*.class  
